import React from 'react';
import {
  LayoutDashboard,
  Shield,
  AlertCircle,
  AlertTriangle,
  Search,
  Settings,
  History,
  Play,
  Kanban,
  Table,
  BarChart2,
  ListChecks,
  Upload,
  LogOut,
  X,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Filter,
  Plus,
  Edit2,
  Trash2,
  Check,
  CheckCircle2,
  XCircle,
  RefreshCw,
  Download,
  Menu,
  MoreHorizontal,
  Package,
  Factory,
  Database,
  ExternalLink,
  Clock,
  Bell,
  GitBranch,
  Info,
  Zap,
  User,
  Users,
  Send,
  Copy,
  Link,
  Tag,
  Sun,
  Moon,
  LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  'dashboard':      LayoutDashboard,
  'shield':         Shield,
  'alert':          AlertCircle,
  'alert-triangle': AlertTriangle,
  'search':         Search,
  'settings':       Settings,
  'history':        History,
  'play':           Play,
  'kanban':         Kanban,
  'table':          Table,
  'chart':          BarChart2,
  'list-checks':    ListChecks,
  'upload':         Upload,
  'logout':         LogOut,
  'x':              X,
  'chevron-down':   ChevronDown,
  'chevron-right':  ChevronRight,
  'chevron-up':     ChevronUp,
  'chevron-left':   ChevronLeft,
  'arrow-right':    ArrowRight,
  'arrow-up':       ArrowUp,
  'arrow-down':     ArrowDown,
  'filter':         Filter,
  'plus':           Plus,
  'edit':           Edit2,
  'trash':          Trash2,
  'check':          Check,
  'check-circle':   CheckCircle2,
  'x-circle':       XCircle,
  'refresh':        RefreshCw,
  'download':       Download,
  'menu':           Menu,
  'more':           MoreHorizontal,
  'package':        Package,
  'factory':        Factory,
  'database':       Database,
  'external':       ExternalLink,
  'clock':          Clock,
  'bell':           Bell,
  'git-branch':     GitBranch,
  'info':           Info,
  'zap':            Zap,
  'user':           User,
  'users':          Users,
  'send':           Send,
  'copy':           Copy,
  'link':           Link,
  'tag':            Tag,
  'sun':            Sun,
  'moon':           Moon,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

export default function Icon({ name, size = 16, className, style }: IconProps) {
  const Component = ICON_MAP[name];
  if (!Component) return null;

  const combined = className ? `icon ${className}` : 'icon';

  return <Component size={size} className={combined} style={style} />;
}
